//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 03:22:27 обнГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.wamdy.com/entitys", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.wamdy.entitys;
