//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.15 at 01:52:39 ÏÂÎç CST 
//


package com.wamdy.entitys;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wamdy.entitys package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wamdy.entitys
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Entitys.Entity.Fields.KeyField }
     * 
     */
    public Entitys.Entity.Fields.KeyField createEntitysEntityFieldsKeyField() {
        return new Entitys.Entity.Fields.KeyField();
    }

    /**
     * Create an instance of {@link Entitys.Entity.Fields }
     * 
     */
    public Entitys.Entity.Fields createEntitysEntityFields() {
        return new Entitys.Entity.Fields();
    }

    /**
     * Create an instance of {@link Entitys.Entity }
     * 
     */
    public Entitys.Entity createEntitysEntity() {
        return new Entitys.Entity();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Entitys }
     * 
     */
    public Entitys createEntitys() {
        return new Entitys();
    }

    /**
     * Create an instance of {@link Entitys.Entity.Fields.NormalField }
     * 
     */
    public Entitys.Entity.Fields.NormalField createEntitysEntityFieldsNormalField() {
        return new Entitys.Entity.Fields.NormalField();
    }

}
